name: update

permissions:
  contents: write

on:
  push:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-24.04
    name: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install 7z zip
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full zip jq
      - name: download
        run: |
          mkdir dist -p
          node download.js

      - name: Download mpv-qjs
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          # name: mpv-v0.41.0-dev-g5dffe4488-pr1-21635437047-x86_64-pc-windows-msvc
          repo: ahaoboy/mpv
          name: ^mpv-.*-x86_64-pc-windows-msvc$
          name_is_regexp: true

      - name: zip mpv-qjs
        run: |
          TARGET_DIR=$(find . -maxdepth 1 -type d -name "mpv-*-x86_64-pc-windows-msvc" | head -n 1)
          if [ -n "$TARGET_DIR" ]; then
              echo "Renaming $TARGET_DIR to ./mpv-qjs"
              mv "$TARGET_DIR" ./mpv-qjs
          else
              echo "Error: Target directory not found"
              exit 1
          fi

          mkdir -p ./mpv-v3
          7z x dist/mpv-v3-win.7z -o./mpv-v3 -y

          cp -r mpv-v3/doc/ mpv-v3/mpv/ mpv-v3/installer/ ./mpv-qjs/
          cp mpv-v3/updater.bat ./mpv-qjs/

          (cd mpv-qjs && zip -r ../dist/mpv-qjs.zip .)

      - name: release
        uses: ncipollo/release-action@v1
        with:
          # name: ${{ steps.get_tag.outputs.tag }}
          # tag: ${{ steps.get_tag.outputs.tag }}
          tag: "nightly"
          name: "nightly"
          artifacts: dist/*
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          commit: main
          replacesArtifacts: true
